clone:
  depth: full    # SonarCloud scanner needs the full history to assign issues properly

# This is a build configuration nobleo-env
image:
  name: nobleo/nobleo-env:melodic
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD

definitions:
  services:
    docker:
      memory: 2048  # Required for sonarcloud step
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &install-build-test-step
        name: Install and build
        # caches:  # Buggy: https://community.sonarsource.com/t/unable-to-register-extension-a-a-a-a-a-a-from-plugin-securitypythonfrontend/25046/7
        #   - sonar
        script:
          - ROSPACKAGE=$BITBUCKET_REPO_SLUG
          # Copy source code in the correct place
          - PACKAGEPATH="${NOBLEO_ENV_DIR}/system/src/$ROSPACKAGE"
          - mkdir -p $PACKAGEPATH && cp -rv . $PACKAGEPATH
          # Perform an install of the dependencies
          - sudo apt-get update -qq
          - source /home/noblean/.nobleo/setup.bash
          - nobleo-get install ros-$ROSPACKAGE sonar-scanner-ci --branch=$BITBUCKET_BRANCH --debug
          # Build the package
          - cd $PACKAGEPATH
          - build-wrapper-linux-x86-64 --out-dir $BW_OUTPUT catkin build --this --no-status
          # Scan for sonarcloud
          - sonar-scanner -Dsonar.cfamily.build-wrapper-output=$BW_OUTPUT -Dsonar.projectVersion=$(git describe)
          # Check the launch dependencies
          # - source "${NOBLEO_DIR}/setup.bash"
          # - rosrun roslaunch roslaunch-check launch
          # Package linter
          - catkin_lint -W2 --strict --explain --ignore unknown_depend
          # Roslint linter (reproduce with `rosrun roslint` etc)
          # - catkin build --this --no-deps --interleave-output --make-args roslint
          # Run tests
          - export ROS_HOSTNAME=localhost
          - catkin build --this --no-deps --no-status --cmake-args -DCATKIN_ENABLE_TESTING=ON --catkin-make-args run_tests
          - catkin_test_results

pipelines:
  default:
    - step: *install-build-test-step
